// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HandwritingRecognition.Model
{
    public class ModelInput
    {
        [ColumnName("Values"), LoadColumn(0, 63)]
        [VectorType(64)]
        public float[] Values;

        [ColumnName("Label"), LoadColumn(64)]
        public float Label { get; set; }
    }
}
