// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace HandwritingRecognition.ModelGenerator
{
    class Program
    {
        static void Main(string[] args)
        {
            ModelBuilder.CreateModel();

            Console.WriteLine("=============== End of process ===============");
        }
    }
}
